import { Montserrat } from "next/font/google"
import "./globals.css"
import { Metadata } from "next"
import Header from "@/components/header"

const mont = Montserrat({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt">
      <body className={mont.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
